text = """Everything was spinning. Almost as a reflex, I shook my head, took a deep breath, and pressed the button again. Surely that had only been an error. It was the first time in forever that someone had pressed it. It was broken. I wasn’t stuck there. I couldn’t be. It simply wasn’t possible. It wasn’t conceivable that I had suffered an accident, lost a leg, fallen into a coma for years, woken up to find myself alone and unable to remember anything, and was trapped there-
“ACCESS DENIED. SECTOR UNDER LOCKDOWN FOR--”
I screamed and punched the door. It hurt a lot, but I closed my eyes and did it again. And again. I only stopped when I heard a weak “ma’am” coming from behind. I snorted, frustrated, and turned around, my eyes wide open again--to the maximum extent they could be. I was shaking. Vac was too--his wheels were dancing randomly on the floor--but I had the impression that was more because he was scared of me.
“M-ma’am,” he said again, “please... don’t hurt yourself like this...”
I looked at my hand. It was red, and commenting on the pain is unnecessary, but I could barely feel it through the adrenaline. None of that felt real. I continued staring down at Vac as I tried to process what I had just heard. Futile. There was nothing to process--the message had already come across. A lot of words had been said by the speaker, and not all of them made sense to me, but that didn’t matter. The way I interpreted them was crystal clear:
“You will never know who you are. You are just a number, Patient 427.”
“You will never see another person again. You better hope that robot outlives you.”
“Those orchids aren’t yours--they are for your grave.”
As these thoughts echoed in my head, a smile spontaneously came across my face. And then my nose started blowing air out. It wasn’t long until the cycle became self-sustaining. When I woke up, I found something as innocent as my mattress being marked by my extended permanence on it funny. But this...? This was the pinnacle of comedy: the story of the most unfortunate woman who had ever lived. I couldn’t stop laughing.
“Ma’am...!” Vac said after a solid minute of my crisis, probably panicking at the sight. “C-calm down... I know this is hard for you, but you clearly aren’t-”
“Aren’t okay? Yeah, I’m not!" I interrupted him as I laughed. “Of course I’m not okay! Don’t you understand? I’m... hah... I’m... hahaha... I’m going to DIE IN HERE! ALONE! WITH A REALLY NICE TALKING VACUUM CLEANER! ISN’T IT HILARIOUS?!”
“N-not really, no...” He replied, his expression worried. “Listen... you should sit down and...”
At this point, everything becomes hazy. Dreamy. I can’t really tell what happened. I probably started ignoring him and wandering off. Where to is unclear. Even more unclear is what I wanted to achieve. I do have flashes of opening the door back into the lobby, and seeing the “1” painted on the wall by the stairs, going up on them, and the elevator doors opening--but not much beyond that. One feeling, however, I can distinctly remember:
The electrical shock of 1200 volts from behind, causing me to pass out."""

open("gen.txt", "w+", encoding="utf-8").write("\n".join([f"<p>{a.strip()}</p>" for a in text.split("\n")]))